dist: trusty
sudo: false
language: python
before_install:
  - export MPLBACKEND='Agg'
  - wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - export MINICONDA_PREFIX="$HOME/miniconda"
  - bash miniconda.sh -b -p $MINICONDA_PREFIX
  - export PATH="$MINICONDA_PREFIX/bin:$PATH"
  - conda config --set always_yes yes
  - conda update -q conda
  - conda info -a
install:
  - wget -q https://data.qiime2.org/distro/core/qiime2-2019.1-py36-linux-conda.yml
  - conda env create -q -n test-env --file qiime2-2019.1-py36-linux-conda.yml
  - source activate test-env
  - conda install -q pytest-cov
  - pip install -q https://github.com/qiime2/q2lint/archive/master.zip
  - export LINT_SOURCE=`python -c "from q2lint._main import main; from inspect import getsourcefile; print(getsourcefile(main))"`
  - export REF_LICENSE=`dirname $LINT_SOURCE`/REF_LICENSE
  - sed -i 's/QIIME 2 development team/Ben Kaehler/' $LINT_SOURCE $REF_LICENSE
  - pip install flake8 coveralls redbiom
  - make install
script:
  - make lint
  - make test-cov
after_success:
  - coveralls
