sudo: false
language: python
python:
  - "3.5"
before_install:
  - export MPLBACKEND='Agg'
  - wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - export MINICONDA_PREFIX="$HOME/miniconda"
  - bash miniconda.sh -b -p $MINICONDA_PREFIX
  - export PATH="$MINICONDA_PREFIX/bin:$PATH"
  - conda config --set always_yes yes
  - conda update -q conda
  - conda info -a
install:
  - conda create -q -n test-env --file https://raw.githubusercontent.com/qiime2/environment-files/master/latest/staging/qiime2-latest-conda-linux-64.txt
  - wget -q https://raw.githubusercontent.com/qiime2/environment-files/master/latest/staging/qiime2-latest-py35-linux-conda.yml
  - conda env create -q -n test-env --file qiime2-latest-py35-linux-conda.yml
  - source activate test-env
  - conda install -q pytest-cov
  - pip install -q https://github.com/qiime2/q2lint/archive/master.zip
  - export LINT_SOURCE=`python -c "from q2lint._main import main; from inspect import getsourcefile; print(getsourcefile(main))"`
  - export REF_LICENSE=`dirname $LINT_SOURCE`/REF_LICENSE
  - sed -i '' 's/QIIME 2 development team/Ben Kaehler/' $LINT_SOURCE $REF_LICENSE
  - conda install -q -c glemaitre imbalanced-learn
  - pip install flake8 coveralls redbiom
  - make install
script:
  - make lint
  - make test-cov
after_success:
  - coveralls
