{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-clawback
  version: "{{ version }}"

source:
  path: ../..

build:
  script: make install
  noarch: generic

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - q2templates >=2018.8.0
    - q2-feature-classifier >=2018.8.0
    - imbalanced-learn
    - redbiom

test:
  imports:
    - q2_clawback
    - qiime2.plugins.clawback

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
