# ci workflow

name: ci

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# mostly stolen from https://github.com/qiime2/q2-feature-classifier/blob/master/.github/workflows/ci.yml
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: checkout source
      uses: actions/checkout@v2

    - name: set up python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: install dependencies
      run: python -m pip install --upgrade pip

    - name: lint
      run: |
        pip install -q https://github.com/qiime2/q2lint/archive/master.zip
        export LINT_SOURCE=`python -c "from q2lint._main import main; from inspect import getsourcefile; print(getsourcefile(main))"`
        export REF_LICENSE=`dirname $LINT_SOURCE`/REF_LICENSE
        sed -i 's/QIIME 2 development team/Ben Kaehler/' $LINT_SOURCE $REF_LICENSE
        q2lint
        pip install -q flake8
        flake8


  build-test-ubuntu:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - name: checkout source
      uses: actions/checkout@v2

    - name: set up python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: download qiime 2 recipe
      run: wget -q https://raw.githubusercontent.com/qiime2/environment-files/master/latest/staging/qiime2-latest-py38-linux-conda.yml

    - name: set up conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: test
        environment-file: qiime2-latest-py38-linux-conda.yml
        python-version: 3.8
        auto-activate-base: false

    - name: install dependencies
      run: |
        conda install pytest-cov
        pip install flake8 coveralls redbiom

    - name: test
      run: |
        make install
        make test-cov

    - name: after-test
      run: coveralls


              #before_install:
              #  - export MPLBACKEND='Agg'
              #  - wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
              #  - export MINICONDA_PREFIX="$HOME/miniconda"
              #  - bash miniconda.sh -b -p $MINICONDA_PREFIX
              #  - export PATH="$MINICONDA_PREFIX/bin:$PATH"
              #  - conda config --set always_yes yes
              #  - conda update -q conda
              #  - conda info -a

    #  build-and-test:
    #    needs: lint
    #    strategy:
    #      matrix:
    #        os: [ubuntu-latest, macos-latest]
    #    runs-on: ${{ matrix.os }}
    #    steps:
    #    - name: checkout source
    #      uses: actions/checkout@v2
    #      with:
    #        fetch-depth: 0
    #
    #    - name: set up python 3.8
    #      uses: actions/setup-python@v1
    #      with:
    #        python-version: 3.8
    #
    #    - name: set up git repo for versioneer
    #      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    #
    #    # necessary until redbiom is updated to 0.3.8 on conda
    #    - name: install redbiom
    #      run: |
    #        pip install numpy
    #        pip install redbiom
    #
    #    - uses: qiime2/action-library-packaging@alpha1
    #      with:
    #        package-name: q2-clawback
    #        build-target: dev
    #        additional-tests: py.test --pyargs q2_clawback
    #        library-token: ${{ secrets.LIBRARY_TOKEN }}
    #

